### ISSUE TITLE
when running 'fab build:outdir=~' getting error 'Fatal error: Couldn't find any fabfiles!'

### ISSUE THREAD

**Issue by chaiweiwei** [card-io/card.io-iOS-source#94]
### Issue description

when running 'fab build:outdir=~' getting error 'Fatal error:
```
fab build:outdir=~

Fatal error: Couldn't find any fabfiles!

Remember that -f can be used to specify fabfile path, and use -h for help.

Aborting.
```
done
```
pip install -r pip_requirements.txt
```

is Baler not install Successful?

**Comment by romk1n** [comment]
@chaiweiwei did you also checked out submodules as per Dev Setup? `git submodule sync; git submodule update --init --recursive`

**Comment by chaiweiwei** [comment]
yes, and the project can build success

**Comment by romk1n** [comment]
hmm that's weird, make sure you run it from the root directory where fabfile.py is

**Comment by chaiweiwei** [comment]
fabfile.py under 'dmz' directory
now, have new error :
```
fab build:outdir=~

Warning: Command(s) not found:
    build

Available commands:

    concat  Regenerate dmz_all.cpp.
```

**Comment by chaiweiwei** [comment]
fabfile.py under 'dmz' directory
now, have new error :
```
fab build:outdir=~

Warning: Command(s) not found:
    build

Available commands:

    concat  Regenerate dmz_all.cpp.
```

.baler_env file content:
```
export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/baler
```

**Comment by chaiweiwei** [comment]
i found 'fabfile.py' file,under the src directory, but when i run 'fab build:outdir=~'
have error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/fabric/1.10.2/libexec/lib/python2.7/site-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/local/Cellar/fabric/1.10.2/libexec/lib/python2.7/site-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/Users/chaiweiwei/Downloads/card.io-iOS-source/src/fabric/fabfile.py", line 7, in <module>
    import nose
ImportError: No module named nose
```
I already 'pip install nose'
